spring:
  application:
    name: project-seed
  profiles:
    active: dev
  # 404 交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher

# 所有环境通用的配置，放在这里
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.airuolin.project.model
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    cache-enabled: true
  lazy-initialization: true
  configuration-properties:
    schema: public

pagehelper:
  helperDialect: mysql
  offset-as-page-num: true
  page-size-zero: true
  reasonable: true
  supportMethodsArguments: true

logging:
  level:
    root: info

# 日志路径
log:
  path: log