# 开发环境配置
# 数据源配置，请修改为你项目的实际配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_auth
    username: root
    password: 1qaz2wsx
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.airuolin.project.mapper: debug
